lettermen_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('utkwebsite.urls')),
    path('admin/', admin.site.urls),
]

utkwebsite/urls.py

from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'utkwebsite'

urlpatterns = [
    path('', views.index, name='index'),
    path('membership', views.membership, name='membership'),
    path('service_award_winners', views.serviceAward, name='service_award'),
    path('honorary_letter_winners', views.letterWinner, name='letterwinner'),
    path('board_of_directors', views.board, name="board"),
    path('service_form', views.service_form, name='service_form'),
    path('letter_winner_form', views.letter_winner_form, name='letter_winner_form'),
    path('board_form', views.board_form, name="board_form"),
    path('contact', views.contact, name="contact"),
    path('about', views.about, name="about"),
    path('events', views.events, name="events")
] 


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utkwebsite/models.py
from django.db import models
from django import forms
from .validators import validate_name, validate_brand
from django.core.validators import MinLengthValidator

# Create your models here.


class ServiceAward(models.Model):
    full_name = models.CharField(max_length=50) # validators=[validate_name]
    sport = models.CharField(max_length=30) #validators=[validate_sport]
    year = models.CharField(max_length=4) #validators=[validate_year]
    # email = models.EmailField()
    statement = models.TextField(blank=False)
    nominator = models.CharField(max_length=50) #validators=[validate_name]

    def __str__(self):
        message = "Full Name: {}, Sport which Nominee lettered in: {}, Year that Nominee graduated: {}, Statement of Support for Nominee: {}, Nominator/Nominated By: {}"
        return message.format(self.full_name, self.sport, self.year, self.statement, self.nominator)


class LetterAward(models.Model):
    full_name = models.CharField(max_length=50) # validators=[validate_name]
    relation = models.CharField(max_length=200) #validators=[validate_relation]
    # email = models.EmailField()
    statement = models.TextField(blank=False)
    nominator = models.CharField(max_length=50) #validators=[validate_name]

    def __str__(self):
        message = "Full Name: {}, Nominee’s Relation to University of Tennessee Athletics: {}, Statement of Support for Nominee: {}, Nominator/Nominated By: {}"
        return message.format(self.full_name, self.relation, self.statement, self.nominator)

class BoardAward(models.Model):
    full_name = models.CharField(max_length=50) # validators=[validate_name]
    sport = models.CharField(max_length=30) #validators=[validate_sport]
    year = models.CharField(max_length=4) #validators=[validate_year]
    # email = models.EmailField()
    statement = models.TextField(blank=False)
    address_one = models.CharField(max_length=50)
    address_two = models.CharField(max_length=50)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=2)
    zip_code = models.CharField(max_length=10)
    phone = models.CharField(max_length=20)
    nominator = models.CharField(max_length=50) #validators=[validate_name]

    def __str__(self):
        message = "Full Name: {}, Sport which Nominee lettered in: {}, Year that Nominee graduated: {}, Statement of Support for Nominee: {}, Address 1: {}, Address 2: {},  City: {}, State: {}, Zip Code: {}, Phone: {}, Nominator/Nominated By: {}"
        return message.format(self.full_name, self.sport, self.year, self.statement, self.address_one, self.address_two, self.city, self.state, self.zip_code, self.phone, self.nominator)

utkwebsite/forms.py
from django.forms import ModelForm
from django.core import validators
from .models import ServiceAward, LetterAward, BoardAward
from django import forms

class ServiceForm(ModelForm):


    class Meta:
        model = ServiceAward
        fields = "__all__"
        widgets = {
            'full_name': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'ex. Thomas Phillip Smith'
                }
            ), 
            'sport': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'ex. Track and Field'
                }
            ), 
            'year': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': 'ex. 1998'
                }
            ),
           
            'statement': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'I support this nominee because... (feel free to copy and paste from wherever you\'ve written your statement)',
                    'cols': '69',
                    'rows': '10',
                }
            ), 
            'nominator': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': 'Your name here'
                }
            ),   
        }
    
    def __init__(self, *args, **kwargs):
        super(ServiceForm, self).__init__(*args, **kwargs)
        self.fields['year'].required = False

class LetterForm(ModelForm):

    class Meta:
        model = LetterAward
        fields = "__all__"
        widgets = {
            'full_name': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'ex. Thomas Phillip Smith'
                }
            ), 
            'relation': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Alumni/Employee/etc.'
                }
            ), 
           
            'statement': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'I support this nominee because... (feel free to copy and paste from wherever you\'ve written your statement)',
                    'cols': '69',
                    'rows': '10',
                }
            ), 
            'nominator': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': 'Your name here'
                }
            ),   
        }
    
    def __init__(self, *args, **kwargs):
        super(LetterForm, self).__init__(*args, **kwargs)

class BoardForm(ModelForm):


    class Meta:
        model = BoardAward
        fields = "__all__"
        widgets = {
            'full_name': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'ex. Thomas Phillip Smith'
                }
            ), 
            'sport': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'ex. Track and Field'
                }
            ), 
            'year': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': 'ex. 1998'
                }
            ),
           
            'statement': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'I support this nominee because... (feel free to copy and paste from wherever you\'ve written your statement)',
                    'cols': '69',
                    'rows': '10',
                }
            ), 

            'address_one': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': '123 Easy St'

                }  
            ),

            'address_two': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': 'Apartment, studio, or floor'

                }  
            ),
            'city': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': 'Anytown'

                }  
            ),
            'state': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': 'TN'

                }  
            ),
            'zip_code': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': '37919'

                }  
            ),
            'phone': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': '(865) 555-1234'

                }  
            ),

            'nominator': forms.TextInput(
                attrs = {
                    'class': 'form-control', 
                    'placeholder': 'Your name here'
                }
            ),   
        }
    
    def __init__(self, *args, **kwargs):
        super(BoardForm, self).__init__(*args, **kwargs)
        self.fields['year'].required = False
        self.fields['address_two'].required = False

utkwebsite/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import ServiceAward, LetterAward, BoardAward
from .forms import ServiceForm, LetterForm, BoardForm
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    return render(request, 'utkwebsite/index.html', {})

def membership(request):
    return render(request, 'utkwebsite/membership.html', {})

def board(request):
    return render(request, 'utkwebsite/board.html', {})

def letterWinner(request):
    return render(request, 'utkwebsite/letterwinner.html', {})

def serviceAward(request):
    return render(request, 'utkwebsite/service_award.html', {})

def contact(request):
    return render(request, 'utkwebsite/contact.html', {})

def about(request):
    return render(request, 'utkwebsite/about.html', {})

def events(request):
    return render(request, 'utkwebsite/events.html', {})

def service_form(request):
    form = ServiceForm(request.POST)

    if request.method == 'POST':
        # form = RegisterForm(request.POST)
    
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            sport = form.cleaned_data['sport']
            year = form.cleaned_data['year']
            statement = form.cleaned_data['statement']
            nominator = form.cleaned_data['nominator']

            print(full_name)
            print(sport)
            print(year)
            print(statement)
            print(nominator)


            # subject = 'Test Message'
            message = "Full Name: {}, Sport which Nominee lettered in: {}, Year that Nominee graduated: {}, Statement of Support for Nominee: {}, Nominator/Nominated By: {}"            # from_email = email
            # recipients = ['growuppod95@gmail.com',]

            print(message.format(full_name, sport, year, statement, nominator))
            form.save()
            # send_mail(subject, message.format(pickDates, attendees, name, reasons, brand), from_email, recipients, fail_silently = False,)
            return HttpResponseRedirect('/')
    
    else:
        form = ServiceForm()


    return render(request, 'utkwebsite/service_form.html', {'form': form})

def letter_winner_form(request):
    form = LetterForm(request.POST)

    if request.method == 'POST':
        # form = RegisterForm(request.POST)
    
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            relation = form.cleaned_data['relation']
            statement = form.cleaned_data['statement']
            nominator = form.cleaned_data['nominator']

            print(full_name)
            print(relation)
            print(statement)
            print(nominator)


            # subject = 'Test Message'
            message = "Full Name: {}, Nominee’s Relation to University of Tennessee Athletics: {}, Statement of Support for Nominee: {}, Nominator/Nominated By: {}"            # from_email = email
            # recipients = ['growuppod95@gmail.com',]

            print(message.format(full_name, relation, statement, nominator))
            form.save()
            # send_mail(subject, message.format(pickDates, attendees, name, reasons, brand), from_email, recipients, fail_silently = False,)
            return HttpResponseRedirect('/')
    
    else:
        form = LetterForm()


    return render(request, 'utkwebsite/letter_winner_form.html', {'form': form})

def board_form(request):
    form = BoardForm(request.POST)

    if request.method == 'POST':
    
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            sport = form.cleaned_data['sport']
            year = form.cleaned_data['year']
            statement = form.cleaned_data['statement']
            address_one = form.cleaned_data['address_one']
            address_two = form.cleaned_data['address_two']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            zip_code = form.cleaned_data['zip_code']
            phone = form.cleaned_data['phone']
            nominator = form.cleaned_data['nominator']

            print(full_name)
            print(sport)
            print(year)
            print(statement)
            print(address_one)
            print(address_two)
            print(city)
            print(state)
            print(zip_code)
            print(phone)
            print(nominator)


            # subject = 'Test Message'
            message = "Full Name: {}, Sport which Nominee lettered in: {}, Year that Nominee graduated: {}, Statement of Support for Nominee: {}, Address 1: {}, Address 2: {},  City: {}, State: {}, Zip Code: {}, Phone: {},  Nominator/Nominated By: {}"
            # recipients = ['growuppod95@gmail.com',]

            print(message.format(full_name, sport, year, statement, address_one, address_two, city, state, zip_code, phone, nominator))
            form.save()
            # send_mail(subject, message.format(pickDates, attendees, name, reasons, brand), from_email, recipients, fail_silently = False,)
            return HttpResponseRedirect('/')
    
    else:
        form = BoardForm()


    return render(request, 'utkwebsite/board_form.html', {'form': form})

utkwebsite/templates/utkwebsite/about.html
{% load static %}
{%include 'utkwebsite/header.html'%}

        <nav class="navbar sticky-top navbar-expand-md py-3 border-bottom border-dark"> 
            <a class="navbar-brand px-md-5" href="https://utsports.com/" target="_blank"><img id="logo" src="{%static '/assets/athletes/powerTLogoWhite.png' %}"></a>
            <a class="navbar-brand" href="/">University of Tennessee T Club</a>
            <!-- Image of power T - link to UT Athletics -->
            <ul class="navbar-nav ml-auto"> 
                <li class="nav-item px-md-2"> <a class="nav-link navbar-text" href="/">Home</a> </li> 
                <li class="nav-item px-md-2"> <a class="nav-link navbar-text" href="{% url 'utkwebsite:about' %}">About</a> </li> 
                <!-- <li class="nav-item dropdown px-md-2"> 
                    <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownMemberMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Membership</a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMemberMenuLink">
                        <li><a class="dropdown-item" href="#">How to Apply</a></li>
                        <li><a class="dropdown-item" href="#">Benefits</a></li>
                        <li><a class="dropdown-item" href="#">Community Impact</a></li>
                    </ul>
                </li>  -->
                <li class="nav-item dropdown px-md-2"> 
                    <a class="nav-link navbar-text" href="{% url 'utkwebsite:events' %}">Events</a>
                  <!--  <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownEventMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Events</a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownEventMenuLink">
                        <li><a class="dropdown-item" href="#">Calendar</a></li>
                        <li><a class="dropdown-item" href="#">Annual Golf Tournament</a></li>
                    </ul>
                -->
                </li> 
                <li class="nav-item dropdown px-md-2"> 
                    <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownAwardMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Honors</a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownAwardMenuLink">
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:service_award' %}">Service Award</a></li>
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:letterwinner' %}">Honorary Letterwinner</a></li>
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:board' %}">Board of Directors</a></li>
                    </ul>
                </li>
                <!-- <li class="nav-item dropdown px-md-2"> 
                    <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownFormMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Forms</a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownFormMenuLink">
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:service_form' %}">Service Award Nomination Form</a></li>
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:letter_winner_form' %}">Honorary Letterwinner Form</a></li>
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:board_form' %}">Board of Directors Form</a></li>
                    </ul>
                </li> -->
                <!-- <li class="nav-item px-md-2"> <a class="nav-link active" href="/">Donate</a> </li> -->
                <li class="nav-item px-md-2"> <a class="nav-link active" href="{% url 'utkwebsite:contact' %}">Contact</a> </li>
                <li class="nav-item px-md-2">
                    <a class="nav-link active btn btn-outline-light" href="{% url 'utkwebsite:membership' %}" role="button">
                        Become a member
                    </a>
                </li>
            </ul> 
        </nav>
        <div class="container-fluid">
            <h3 class="text-center mt-3">Our History</h3>
            
            <p id="aboutIntro">
                According to <a href="https://volopedia.lib.utk.edu/entries/lettermens-t-club/" target="_blank">Betsey B. Creekmore</a>, 

                all individuals who have been awarded a varsity letter “T” in an NCAA-sanctioned intercollegiate sport at UT are considered members of the Letterwinner’s Club, first formed in 1903. 
                The Club has decided to give all Letterwinners a lifelong pass for admission to all forms of athletics on the Hill, and to have special, reserved places for them at athletic events.



            </p>

            <div class="athletePhotoGallery">
                <div id="athIndicators" class="carousel slide pb-5" data-ride="carousel">
                    <!-- <ol class="carousel-indicators">
                        <li data-target="#athIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#athIndicators" data-slide-to="1"></li>
                        <li data-target="#athIndicators" data-slide-to="2"></li>
                    </ol> -->
                    <div class="carousel-inner">
                
                    
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="static/assets/athletes/utk2.jpeg" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="static/assets/athletes/utk3.jpeg" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-50 mx-auto" src="static/assets/athletes/utk6.jpeg" alt="Third slide">
                        </div>
                       
              
                    
                    </div>
                    <a class="carousel-control-prev" href="#athIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#athIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            <!-- <h3 class="text-center mt-3">Our Legacy</h3>
            <p id="wallOfFame">
                The Lettermen’s Wall of Fame is located in front of the Neyland-Thompson Sports Center. 
                Funded by private contributions from the Lettermen’s “T” Club, the wall contains the names of all men and women athletes, 
                managers and trainers whose performance has been recognized by award of the “T” dating back to 1891. An initial list of more 
                than 5,500 names was generated. The wall is constructed of Tennessee marble and concrete and was dedicated November 18, 2000, 
                after more than two years’ of work and construction.
            </p> -->
            
           

            </div>
            
        
        <footer>
            
        </footer>



        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <script>
            $(document).ready(function() {
  jQuery.fn.carousel.Constructor.TRANSITION_DURATION = 4000  // 4 seconds
});
            </script>
    </body>

</html>

utkwebsite/templates/utkwebsite/contact.html
{% load static %}
{%include 'utkwebsite/header.html'%}

        <div class="container-fluid">
            <h2 class="text-center mt-3" id="contactTitle">Contact the T Club</h2>
            <hr/>
            <div class="row">
                <h3 class="mx-auto">Email: <a id="contactEmail" href="mailto:T-Club@utk.edu">T-Club@utk.edu</a> </h3>
            </div>
            <div class="row">
                <h3 class="mx-auto">Phone: <a id="contactPhoneNumber" href="tel:(865) 974-9054">865-974-9054</a></h3>
                
            </div>
            <hr/>
            <br>
                <h3 class="text-center">Mailing Address: </h3>
                <br>
                <address class="text-center" id="contactAddress">
                    <strong>Letter Winner's T Club</strong>
                    <br>
                    PO Box 47
                    <br>
                    Knoxville, TN 37901
                
                </address>
            
          <!--  <div class="row">
                <h3>Office: </h3>
                <p id="officeAddress">
              
                
                </p>
            </div>
-->
            <hr/>
            
                <h4 class="text-center">If you'd like to stay up to date with the T club, please join by downloading our app:</h4>
                <a class="nav-link active btn btn-outline-dark w-25 mx-auto" href="{% url 'utkwebsite:membership' %}" role="button">
                    Download
                </a>
            
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


        </body>
        </html>

utkwebsite/templates/utkwebsite/endBody.html
<!-- {% load static %} -->

       
       <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <!-- <script src="{% static 'js/canvas.js' %}"></script>    -->

utkwebsite/templates/utkwebsite/events.html
{% load static %}
{%include 'utkwebsite/header.html'%}

<iframe src="https://calendar.google.com/calendar/embed?src=74a3qjmaqvdukelrbbp2do2fmgilf17h%40import.calendar.google.com&ctz=America%2FNew_York" 
style="border: 0; margin-left: 5%" width="90%" height="600" frameborder="0" scrolling="no" class="fullscreen"></iframe>

<hr>

<h2 class="text-center">Announcements</h2>
<p class="text-center">Currently, no announcements</p>
</body>

</html>

{%include 'utkwebsite/endBody.html'%}

utkwebsite/templates/utkwebsite/header.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>University of Tennessee T Club</title>
        {% load static %}

        <link rel="stylesheet"  href="{%static  'css/index.css'  %}">
        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Poppins">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div class="checkerboard">


        </div>


        <nav class="navbar sticky-top navbar-expand-md py-3 border-bottom border-dark"> 
            <a class="navbar-brand px-md-5" href="https://utsports.com/" target="_blank"><img id="logo" src="{%static '/assets/athletes/powerTLogoWhite.png' %}"></a>
            <h4 id="navTitle" href="/">University of Tennessee T Club</h4>
            <!-- Image of power T - link to UT Athletics -->
            <ul class="navbar-nav ml-auto"> 
                <li class="nav-item px-md-2 h4"> <a class="nav-link navbar-text" href="/">Home</a> </li> 
                <li class="nav-item px-md-2 h4"> <a class="nav-link navbar-text" href="{% url 'utkwebsite:about' %}">About</a> </li> 
                <!-- <li class="nav-item dropdown px-md-2"> 
                    <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownMemberMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Membership</a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMemberMenuLink">
                        <li><a class="dropdown-item" href="#">How to Apply</a></li>
                        <li><a class="dropdown-item" href="#">Benefits</a></li>
                        <li><a class="dropdown-item" href="#">Community Impact</a></li>
                    </ul>
                </li>  -->
                <li class="nav-item dropdown px-md-2 h4"> 
                    <a class="nav-link navbar-text" href="{% url 'utkwebsite:events' %}">Events</a>
                  <!--  <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownEventMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Events</a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownEventMenuLink">
                        <li><a class="dropdown-item" href="#">Calendar</a></li>
                        <li><a class="dropdown-item" href="#">Annual Golf Tournament</a></li>
                    </ul>
                -->
                </li> 
                <li class="nav-item dropdown px-md-2 h4"> 
                    <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownAwardMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Honors</a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownAwardMenuLink">
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:service_award' %}">Service Award</a></li>
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:letterwinner' %}">Honorary Letterwinner</a></li>
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:board' %}">Board of Directors</a></li>
                    </ul>
                </li>
                <!-- <li class="nav-item dropdown px-md-2"> 
                    <a class="nav-link dropdown-toggle" href="/" id="navbarDropdownFormMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Forms</a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownFormMenuLink">
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:service_form' %}">Service Award Nomination Form</a></li>
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:letter_winner_form' %}">Honorary Letterwinner Form</a></li>
                        <li><a class="dropdown-item" href="{% url 'utkwebsite:board_form' %}">Board of Directors Form</a></li>
                    </ul>
                </li> -->
                <!-- <li class="nav-item px-md-2"> <a class="nav-link active" href="/">Donate</a> </li> -->
                <li class="nav-item px-md-2 h4"> <a class="nav-link active" href="{% url 'utkwebsite:contact' %}">Contact</a> </li>
                <li class="nav-item px-md-2 d-none d-lg-block">
                    <a class="nav-link active btn btn-outline-light" href="{% url 'utkwebsite:membership' %}" role="button">
                        Become a member
                    </a>
                </li>
            </ul> 
        </nav>